server:
  port: 8085

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.example526.dao.entity
  mapperLocations: classpath:mapper/*.xml
  #开始MyBatis的二级缓存
  configuration:
    cache-enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myweb?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

